export var dataBase = [
  {
    id: 1,
    nome: 'Carlos',
    sobrenome: 'Andrade',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 20,
    notaDois: 20,
    notaTres: 20,
    notaQuatro: 20,
    notaFinal: 80,
  },
  {
    id: 2,
    nome: 'Larissa',
    sobrenome: 'Almeida',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 21,
    notaDois: 12,
    notaTres: 23,
    notaQuatro: 10,
    notaFinal: 66,
  },
  {
    id: 3,
    nome: 'Lara',
    sobrenome: 'Alencar',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 21,
    notaDois: 12,
    notaTres: 23,
    notaQuatro: 10,
    notaFinal: 66,
  },
  {
    id: 4,
    nome: 'Emanuelle',
    sobrenome: 'Cruz',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 21,
    notaDois: 11,
    notaTres: 13,
    notaQuatro: 14,
    notaFinal: 59,
  },
  {
    id: 5,
    nome: 'Diogo',
    sobrenome: 'Costa',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 20,
    notaDois: 20,
    notaTres: 23,
    notaQuatro: 10,
    notaFinal: 73,
  },
  {
    id: 6,
    nome: 'Roberto',
    sobrenome: 'Silva',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 25,
    notaDois: 25,
    notaTres: 20,
    notaQuatro: 20,
    notaFinal: 90,
  },
  {
    id: 7,
    nome: 'Ricardo',
    sobrenome: 'Almeida',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 25,
    notaDois: 25,
    notaTres: 25,
    notaQuatro: 23,
    notaFinal: 98,
  },
  {
    id: 8,
    nome: 'Clara',
    sobrenome: 'Memento',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 18,
    notaDois: 18,
    notaTres: 24,
    notaQuatro: 25,
    notaFinal: 85,
  },
  {
    id: 9,
    nome: 'Lucas',
    sobrenome: 'Ribeiro',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 9,
    notaDois: 18,
    notaTres: 21,
    notaQuatro: 17,
    notaFinal: 65,
  },
  {
    id: 10,
    nome: 'Julia',
    sobrenome: 'Silverio',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 19,
    notaDois: 18,
    notaTres: 21,
    notaQuatro: 7,
    notaFinal: 65,
  },
  {
    id: 11,
    nome: 'Marina',
    sobrenome: 'Torino',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 23,
    notaDois: 24,
    notaTres: 21,
    notaQuatro: 17,
    notaFinal: 85,
  },
  {
    id: 12,
    nome: 'Pedro',
    sobrenome: 'Torino',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
    notaUm: 3,
    notaDois: 24,
    notaTres: 22,
    notaQuatro: 25,
    notaFinal: 74,
  },
];

// DATA BASE PROFESSORES
export var dataBaseProfessores = [
  {
    id: 1,
    nome: 'João',
    sobrenome: 'Costa',
    email: 'jaoc@gmail.com',
    senha: 'senha',
    disciplina: 'HISTORIA',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
  },
  {
    id: 2,
    nome: 'Ana',
    sobrenome: 'Silva',
    email: 'aninha@gmail.com',
    senha: 'senha',
    disciplina: 'PORTUGUES',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
  },
  {
    id: 3,
    nome: 'Camila',
    sobrenome: 'Peixoto',
    email: 'mila@gmail.com',
    senha: 'senha',
    disciplina: 'INGLES',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
  },
  {
    id: 4,
    nome: 'Vander',
    sobrenome: 'Arantes',
    email: 'vante@gmail.com',
    senha: 'senha',
    disciplina: 'INGLES',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
  },
  {
    id: 5,
    nome: 'Edson',
    sobrenome: 'Silverio',
    email: 'vante@gmail.com',
    senha: 'senha',
    disciplina: 'MATEMATICA',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
  },
  {
    id: 6,
    nome: 'Jorge',
    sobrenome: 'Arantes',
    email: 'vante@gmail.com',
    senha: 'senha',
    disciplina: 'MATEMATICA',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
  },
  {
    id: 7,
    nome: 'Eliane',
    sobrenome: 'Oliveira',
    email: 'vante@gmail.com',
    senha: 'senha',
    disciplina: 'PORTUGUES',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
  },
  {
    id: 8,
    nome: 'Agnes',
    sobrenome: 'Oliveira',
    email: 'vante@gmail.com',
    senha: 'senha',
    disciplina: 'PORTUGUES',
    rua: 'Rua das Palmeiras',
    bairro: 'Bela Vista',
    numero: 120,
    complemento: 'Casa',
    cep: '37410000',
    cidade: 'TRES CORACOES',
    estado: 'MG',
  },
];
